GET http://localhost:3333/movements

### 
POST http://localhost:3333/movements
Content-Type: application/json

{
  "companies_id": 1,
  "movement_type": "compra",
  "amount": 100,
  "description": "venta de lechugas amargas"
}

###
PATCH http://localhost:3333/movements
Content-Type: application/json

{
  "id": 4,
  "companies_id": 1,
  "movement_type": "venta actualizada otra vez",
  "amount": 500,
  "description": "ventan de actualizacion completada"
}

###
DELETE http://localhost:3333/movements
Content-Type: application/json 

{
  "id": 4
}