POST http://localhost:3333/users/signup
Content-Type: application/json

{
  "companies_id": 1,
  "name": "calefdasd",
  "email": "calegdasdonsale@gmail.com",
  "password": "dadaasdopfg",
  "rol": "admian"
}

