POST http://localhost:3333/register
Content-Type: application/json

{
  "name": "google",
  "email": "google@google.com",
  "phone": "+0000000",
  "address": "estado unidos",
  "password": "dasjdfasbfa",
  "state": true
}

